#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#    Listens on port 80.
#    Returns a page containing "Hello World" when queried
#    at the root with a curl GET request.

# Install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Configuration
mkdir /etc/nginx/html

# Creating Sample Page
echo "Hello World!" > /var/www/html/index.html

# Creating Server Block Files
echo "server {
	listen 80 default_server;
        listen [::]:80 default_server;

	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;
}
" > /etc/nginx/sites-available/default

# Restart Nginx
nginx -s reload
